#!/usr/bin/env ruby
require './app'
def desplay_all_activity
  puts 'Please Choose an option by enterin a number:'
  puts '1- List all Book'
  puts '2- List all Person'
  puts '3- Create a Person'
  puts '4- Create a Book'
  puts '5- Create a Rental'
  puts '6- List a Rental with a given ID'
  puts '7- Exit'
end

def create_student_or_teacher(app, num)
  case num
  when 1
    app.create_studnet
  when 2
    app.add_teacher
  end
end

def select_one_activity(app, input)
  case input
  when 1
    app.list_book
  when 2
    app.list_person
  when 3
    print 'Do you want ot create student (1) or teacher (2)? [Intput the number]: '
    num = gets.chomp.to_i
    create_student_or_teacher(app, num)
  when 4
    app.create_book
  when 5
    app.create_rental
  when 6
    app.list_rental_for_person
  end
end

def main
  puts ['Welcome To School Library App!', ' ']
  app = App.new
  input = 0
  until input == 7
    desplay_all_activity
    input = gets.to_i
    puts 'Invalid choice, please select a number from [1..7]' if input < 1 || input > 7
    select_one_activity(app, input)
  end
end
main
